### ISSUE TITLE
Paired Image to Image Translation

### ISSUE THREAD

**Issue by BEpresent** [NVlabs/imaginaire#10]
paired Image to Image Translation

Thank you very much for the awesome library!

I want to perform a paired image to image translation like in the previous pix2pixHD implementation without any label or instance maps, i.e. image from domain A -> domain B.

In the previous implementation, one had to set

> 
> If your input is not a label map, please just specify --label_nc 0 which will directly use the RGB colors as input. The folders should then be named train_A, train_B instead of train_label, train_img, where the goal is to translate images from A to B.
> If you don't have instance maps or don't want to use them, please specify --no_instance.

How can this be done in the imaginaire implementation? 

In the yaml file, I set
```


    type: imaginaire.datasets.paired_images    
    num_workers: 4
    input_types:
        - images:
            ext: png
            num_channels: 3
            interpolator: BILINEAR
            normalize: True
            #use_dont_care: True
        - seg_maps:
            ext: png
            num_channels: 3 # 35
            interpolator: BILINEAR
            normalize: True
            #use_dont_care: True
        #- instance_maps:
        #    ext: png
        #    num_channels: 1
        #    interpolator: NEAREST
        #    normalize: False
        #    use_dont_care: True
    
    input_image:
        - images

    input_labels:
        - seg_maps
        #- instance_maps
```

i.e. the instance maps are commented out and instead of 'train_A'  I use seg_maps as the source image directory that shall be translated to the directory 'images'. is this the way to do it here?

The output images are 4 columns. What is the meaning of the columns ? Column 1 seems to be the input image column 2 seems to be a label map. Columns 3 and 4 do look almost identical to column 1 (probably the synthesized images), therefore it seems that something went wrong with my settings, as no translation has been performed.

Could SPADE be used in an identical way or can the SPADE generator be used as a replacement for pix2pixHD ?
