### ISSUE TITLE
How to do example guided image generation, as shown in Fig.1 of the GauGAN paper?

### ISSUE THREAD

**Issue by Ha0Tang** [NVlabs/imaginaire#22]

**Comment by mingyuliutw** [comment]
You need to add 
```
- images:
            ext: jpg
            num_channels: 3
            interpolator: BILINEAR
            normalize: True
            use_dont_care: False
```
to test_data
in 
https://github.com/NVlabs/imaginaire/blob/master/configs/projects/spade/cocostuff/base128_bs4.yaml
