### ISSUE TITLE
Input to Pix2pixHD is an RGB image not a label map

### ISSUE THREAD

**Issue by lingjie0206** [NVlabs/imaginaire#54]
Hi, if the input to pix2pixHD is not a label map but an RGB image, what's the easiest way to achieve this? Thanks!

**Comment by arunmallya** [comment]
Have a look at the sample config: https://github.com/NVlabs/imaginaire/blob/master/configs/projects/pix2pixHD/cityscapes/ampO1.yaml#L83-L105

Set 
```
input_types:
        - images:
            ext: png
            num_channels: 3
            interpolator: BILINEAR
            normalize: True
        - rgb_labels:
            ext: png
            num_channels: 3
            interpolator: BILINEAR
            normalize: False/True (depends on if you want [0, 1] or [-1, 1] range)

input_image:
        - images
            
input_labels:
        - rgb_labels
```

Also create the LMDB appropriately.
